spring:
  datasource:
    url: jdbc:mysql://localhost:3307/vatest
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  batch:
    jdbc:
      initialize-schema: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  sql:
    init:
      mode: never  # Prevents Spring Boot from executing schema.sql/data.sql if they exist
